In [1]:
import queries
import csv
import functions as fx
import pandas as pd

In [2]:
rankings = [5,4,3,2,1]
for ranking in rankings:
    query = queries.get_query_KevinRating(ranking)
    temp = (fx.connDBAndReturnDF(query))
    if (ranking == 5):
        fivestars = temp
        print(fivestars.shape[0])
    elif (ranking == 4):
        fourstars = temp.query("ID not in @fivestars.ID")
        print(fourstars.shape[0])
    elif (ranking == 3):
        threestars = temp.query("ID not in @fourstars.ID")
        print(threestars.shape[0])
    elif (ranking == 2):
        twostars = temp.query("ID not in @threestars.ID")
        print(twostars.shape[0])
    elif (ranking == 1):
        onestar = temp.query("ID not in @twostars.ID")
        print(onestar.shape[0])
    del temp

876
3070
9303
11312
46898

In [3]:
frames = [fivestars, fourstars, threestars, twostars, onestar]
allplayers = pd.concat(frames)
print(allplayers.shape[0])

71459

In [4]:
allplayers.to_csv(path_or_buf = 'allplayers.csv', sep = ',')

In [5]:
pd.set_option('display.max_columns', None)
allplayers

,ID,IDYR,College,conference,Year,PlayerName,HighSchool,City,State,Position,Height,Weight,CompositeRating,CompositeStars,CompositeNationalRank,CompositePositionRank,CompositeStateRank,Rating247,Stars247,NationalRank247,PositionRank247,StateRank247,StarsRivals,NationalRankRivals,PositionRankRivals,StateRankRivals,NFLDraftRound,NFLDraftPick,NFLAllProFirstTeam,NFLProBowl,NFLYearsAsStarter,NFLGamesPlayed,AllConferenceTeam_Best,NCAAGamesPlayed,NCAAGamesStarted,AllAmericanBest,HornbeakRating
0,aaronross_texas,aaronross_texas_2002,texas,bigtwelve,2002,aaronross,John Tyler,Tyler,TX,DB,73.0,180.0,0.9,4,158.0,9.0,25.0,NaN,1,NaN,NaN,NaN,4,NaN,NaN,NaN,1.0,20.0,0.0,0.0,4.0,83,1.0,NaN,NaN,NaN,5
1,adamcarriker_nebraska,adamcarriker_nebraska_2002,nebraska,bigten,2002,adamcarriker,Kennewick,Kennewick,WA,DE,78.0,235.0,0.8,3,694.0,41.0,10.0,NaN,1,NaN,NaN,NaN,3,NaN,46.0,NaN,1.0,13.0,0.0,0.0,3.0,65,1.0,NaN,NaN,NaN,5
2,adamjones_westvirginia,adamjones_westvirginia_2002,westvirginia,bigtwelve,2002,adamjones,Westlake,Atlanta,GA,DB,72.0,185.0,0.7667,2,NaN,142.0,89.0,NaN,1,NaN,NaN,NaN,2,NaN,71.0,NaN,1.0,6.0,1.0,1.0,6.0,146,1.0,NaN,NaN,1.0,5
3,ajhawk_ohiostate,ajhawk_ohiostate_2002,ohiostate,bigten,2002,ajhawk,Centerville,Dayton,OH,LB,74.0,230.0,0.8333,3,543.0,28.0,24.0,NaN,1,NaN,NaN,NaN,3,NaN,30.0,NaN,1.0,5.0,0.0,0.0,10.0,159,1.0,NaN,NaN,1.0,5
4,alexsmith_utah,alexsmith_utah_2002,utah,pactwelve,2002,alexsmith,Helix,La Mesa,CA,QB,75.0,190.0,0.7667,2,NaN,39.0,137.0,NaN,1,NaN,NaN,NaN,2,NaN,NaN,NaN,1.0,1.0,0.0,3.0,14.0,174,1.0,NaN,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46941,zykeiusstrong_houston,None,houston,None,2021,zykeiusstrong,None,None,None,DL,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,1
46942,zylanperry_louisiana,None,louisiana,None,2021,zylanperry,None,None,None,RB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,1.0,0.0,NaN,1
46943,zymcdonald_louisiana,None,louisiana,None,2021,zymcdonald,None,None,None,QB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,1.0,0.0,NaN,1
46944,zymircobbs_temple,None,temple,None,2021,zymircobbs,None,None,None,DL,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,1.0,0.0,NaN,1
46945,zyunreeves_northcarolinastate,None,northcarolinastate,None,2021,zyunreeves,None,None,None,DL,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,2.0,0.0,NaN,1

In [6]:
fivestars

,ID,IDYR,College,conference,Year,PlayerName,HighSchool,City,State,Position,Height,Weight,CompositeRating,CompositeStars,CompositeNationalRank,CompositePositionRank,CompositeStateRank,Rating247,Stars247,NationalRank247,PositionRank247,StateRank247,StarsRivals,NationalRankRivals,PositionRankRivals,StateRankRivals,NFLDraftRound,NFLDraftPick,NFLAllProFirstTeam,NFLProBowl,NFLYearsAsStarter,NFLGamesPlayed,AllConferenceTeam_Best,NCAAGamesPlayed,NCAAGamesStarted,AllAmericanBest,HornbeakRating
0,aaronross_texas,aaronross_texas_2002,texas,bigtwelve,2002,aaronross,John Tyler,Tyler,TX,DB,73.0,180.0,0.9,4,158.0,9.0,25.0,NaN,1,NaN,NaN,NaN,4,NaN,NaN,NaN,1.0,20.0,0.0,0.0,4.0,83,1.0,NaN,NaN,NaN,5
1,adamcarriker_nebraska,adamcarriker_nebraska_2002,nebraska,bigten,2002,adamcarriker,Kennewick,Kennewick,WA,DE,78.0,235.0,0.8,3,694.0,41.0,10.0,NaN,1,NaN,NaN,NaN,3,NaN,46.0,NaN,1.0,13.0,0.0,0.0,3.0,65,1.0,NaN,NaN,NaN,5
2,adamjones_westvirginia,adamjones_westvirginia_2002,westvirginia,bigtwelve,2002,adamjones,Westlake,Atlanta,GA,DB,72.0,185.0,0.7667,2,NaN,142.0,89.0,NaN,1,NaN,NaN,NaN,2,NaN,71.0,NaN,1.0,6.0,1.0,1.0,6.0,146,1.0,NaN,NaN,1.0,5
3,ajhawk_ohiostate,ajhawk_ohiostate_2002,ohiostate,bigten,2002,ajhawk,Centerville,Dayton,OH,LB,74.0,230.0,0.8333,3,543.0,28.0,24.0,NaN,1,NaN,NaN,NaN,3,NaN,30.0,NaN,1.0,5.0,0.0,0.0,10.0,159,1.0,NaN,NaN,1.0,5
4,alexsmith_utah,alexsmith_utah_2002,utah,pactwelve,2002,alexsmith,Helix,La Mesa,CA,QB,75.0,190.0,0.7667,2,NaN,39.0,137.0,NaN,1,NaN,NaN,NaN,2,NaN,NaN,NaN,1.0,1.0,0.0,3.0,14.0,174,1.0,NaN,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,joetryonshoyinka_washington,None,washington,pactwelve,2021,joetryonshoyinka,None,None,None,LB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1.0,32.0,0.0,0.0,0.0,23,NaN,NaN,NaN,NaN,5
872,justinfields_ohiostate,None,ohiostate,None,2021,justinfields,None,None,None,QB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1.0,11.0,0.0,0.0,0.0,18,NaN,NaN,NaN,NaN,5
873,mikerose_iowastate,None,iowastate,None,2021,mikerose,None,None,None,LB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,1.0,NaN,NaN,1.0,5
874,odafeoweh_pennstate,None,pennstate,None,2021,odafeoweh,None,None,None,DE,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1.0,31.0,0.0,0.0,0.0,21,NaN,NaN,NaN,NaN,5
875,treylance_northdakotast,None,northdakotast,None,2021,treylance,None,None,None,QB,NaN,NaN,None,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1.0,3.0,0.0,0.0,0.0,8,NaN,NaN,NaN,NaN,5

In [7]:
fx.connAndWriteDB(allplayers, 'HornbeakRatings')